/** GENERATED by scripts/build-gallery.mjs — do not edit by hand. */

export interface GalleryCategory {
  id: string;
  title: string;
  photos: string[];
}

export const GALLERY: GalleryCategory[] = [
  {
    "id": "accident-repairs",
    "title": "Accident Repairs",
    "photos": [
      "/gallery/accident-repairs/01.jpg",
      "/gallery/accident-repairs/02.jpg",
      "/gallery/accident-repairs/03.jpg",
      "/gallery/accident-repairs/04.jpg",
      "/gallery/accident-repairs/05.jpg",
      "/gallery/accident-repairs/06.jpg",
      "/gallery/accident-repairs/07.jpg",
      "/gallery/accident-repairs/08.jpg",
      "/gallery/accident-repairs/09.jpg",
      "/gallery/accident-repairs/10.jpg"
    ]
  },
  {
    "id": "body-kits",
    "title": "Customisations",
    "photos": [
      "/gallery/body-kits/01.jpg",
      "/gallery/body-kits/02.jpg",
      "/gallery/body-kits/03.jpg",
      "/gallery/body-kits/04.jpg",
      "/gallery/body-kits/05.jpg",
      "/gallery/body-kits/06.jpg",
      "/gallery/body-kits/07.jpg",
      "/gallery/body-kits/08.jpg",
      "/gallery/body-kits/09.jpg",
      "/gallery/body-kits/10.jpg",
      "/gallery/body-kits/11.jpg",
      "/gallery/body-kits/12.jpg",
      "/gallery/body-kits/13.jpg",
      "/gallery/body-kits/14.jpg",
      "/gallery/body-kits/15.jpg",
      "/gallery/body-kits/16.jpg",
      "/gallery/body-kits/17.jpg",
      "/gallery/body-kits/18.jpg",
      "/gallery/body-kits/19.jpg",
      "/gallery/body-kits/20.jpg",
      "/gallery/body-kits/21.jpg",
      "/gallery/body-kits/22.jpg",
      "/gallery/body-kits/23.jpg",
      "/gallery/body-kits/24.jpg",
      "/gallery/body-kits/25.jpg",
      "/gallery/body-kits/26.jpg",
      "/gallery/body-kits/27.jpg",
      "/gallery/body-kits/28.jpg",
      "/gallery/body-kits/29.jpg",
      "/gallery/body-kits/30.jpg",
      "/gallery/body-kits/31.jpg",
      "/gallery/body-kits/32.jpg",
      "/gallery/body-kits/33.jpg",
      "/gallery/body-kits/34.jpg",
      "/gallery/body-kits/35.jpg",
      "/gallery/body-kits/36.jpg",
      "/gallery/body-kits/37.jpg",
      "/gallery/body-kits/38.jpg",
      "/gallery/body-kits/39.jpg",
      "/gallery/body-kits/40.jpg",
      "/gallery/body-kits/41.jpg",
      "/gallery/body-kits/42.jpg",
      "/gallery/body-kits/43.jpg",
      "/gallery/body-kits/44.jpg"
    ]
  },
  {
    "id": "restorations",
    "title": "Restorations",
    "photos": [
      "/gallery/restorations/01.jpg",
      "/gallery/restorations/02.jpg",
      "/gallery/restorations/03.jpg",
      "/gallery/restorations/04.jpg",
      "/gallery/restorations/05.jpg",
      "/gallery/restorations/06.jpg",
      "/gallery/restorations/07.jpg",
      "/gallery/restorations/08.jpg",
      "/gallery/restorations/09.jpg",
      "/gallery/restorations/10.jpg",
      "/gallery/restorations/11.jpg"
    ]
  },
  {
    "id": "tints-sprays-wraps",
    "title": "Sprays & Wraps",
    "photos": [
      "/gallery/tints-sprays-wraps/01.jpg",
      "/gallery/tints-sprays-wraps/02.jpg",
      "/gallery/tints-sprays-wraps/03.jpg",
      "/gallery/tints-sprays-wraps/04.jpg",
      "/gallery/tints-sprays-wraps/05.jpg",
      "/gallery/tints-sprays-wraps/06.jpg",
      "/gallery/tints-sprays-wraps/07.jpg",
      "/gallery/tints-sprays-wraps/08.jpg",
      "/gallery/tints-sprays-wraps/09.jpg",
      "/gallery/tints-sprays-wraps/10.jpg",
      "/gallery/tints-sprays-wraps/11.jpg",
      "/gallery/tints-sprays-wraps/12.jpg",
      "/gallery/tints-sprays-wraps/13.jpg",
      "/gallery/tints-sprays-wraps/14.jpg",
      "/gallery/tints-sprays-wraps/15.jpg",
      "/gallery/tints-sprays-wraps/16.jpg",
      "/gallery/tints-sprays-wraps/17.jpg",
      "/gallery/tints-sprays-wraps/18.jpg",
      "/gallery/tints-sprays-wraps/19.jpg"
    ]
  },
  {
    "id": "smart-repairs",
    "title": "SMART Repairs",
    "photos": [
      "/gallery/smart-repairs/01.jpg",
      "/gallery/smart-repairs/02.jpg",
      "/gallery/smart-repairs/03.jpg",
      "/gallery/smart-repairs/04.jpg",
      "/gallery/smart-repairs/05.jpg",
      "/gallery/smart-repairs/06.jpg",
      "/gallery/smart-repairs/07.jpg",
      "/gallery/smart-repairs/08.jpg",
      "/gallery/smart-repairs/09.jpg",
      "/gallery/smart-repairs/10.jpg",
      "/gallery/smart-repairs/11.jpg",
      "/gallery/smart-repairs/12.jpg",
      "/gallery/smart-repairs/13.jpg",
      "/gallery/smart-repairs/14.jpg",
      "/gallery/smart-repairs/15.jpg",
      "/gallery/smart-repairs/16.jpg",
      "/gallery/smart-repairs/17.jpg",
      "/gallery/smart-repairs/18.jpg",
      "/gallery/smart-repairs/19.jpg"
    ]
  }
];
