/**
 * Gallery asset pipeline — one-shot.
 *
 * Reads Arvin's curated screenshot set (unzipped to a temp dir), optimises
 * every photo with sharp (max width 800, q78, metadata stripped) into
 * public/gallery/<category-id>/NN.jpg, and emits the manifest module the
 * GalleryWheel imports. Categories map onto the site's canonical service ids.
 *
 *   node scripts/build-gallery.mjs [path-to-unzipped-folder]
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import sharp from "sharp";

const ZIP = path.join(
  process.env.HOME,
  "Downloads",
  "rtperformance-screenshots-curated.zip"
);

/** zip folder → site category (canonical service order) */
const CATEGORIES = [
  { src: "accident-repair", id: "accident-repairs", title: "Accident Repairs" },
  { src: "body-kit-and-customisations", id: "body-kits", title: "Body Kits & Customisations" },
  { src: "restorations", id: "restorations", title: "Restorations" },
  { src: "tints-sprays-and-wraps", id: "tints-sprays-wraps", title: "Tints, Sprays & Wraps" },
  { src: "smart-repair", id: "smart-repairs", title: "SMART Repairs" },
];

const repo = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const outRoot = path.join(repo, "public", "gallery");

// -- source: arg, or unzip fresh into a temp dir
let srcRoot = process.argv[2];
let tempDir = null;
if (!srcRoot) {
  tempDir = path.join(tmpdir(), `rt-gallery-${Date.now()}`);
  mkdirSync(tempDir, { recursive: true });
  execFileSync("unzip", ["-q", ZIP, "-d", tempDir]);
  srcRoot = path.join(tempDir, "rtperformance-screenshots-curated");
}
if (!existsSync(srcRoot)) {
  console.error(`source not found: ${srcRoot}`);
  process.exit(1);
}

rmSync(outRoot, { recursive: true, force: true });

const manifest = [];
let total = 0;

for (const cat of CATEGORIES) {
  const dir = path.join(srcRoot, cat.src);
  const files = readdirSync(dir)
    .filter((f) => /\.(jpe?g|png)$/i.test(f) && !f.startsWith("."))
    .sort();
  const outDir = path.join(outRoot, cat.id);
  mkdirSync(outDir, { recursive: true });

  const photos = [];
  for (let i = 0; i < files.length; i++) {
    const name = `${String(i + 1).padStart(2, "0")}.jpg`;
    await sharp(path.join(dir, files[i]))
      .rotate() // honour EXIF orientation, then strip it
      .resize({ width: 800, withoutEnlargement: true })
      .jpeg({ quality: 78, mozjpeg: true })
      .toFile(path.join(outDir, name));
    photos.push(`/gallery/${cat.id}/${name}`);
  }
  manifest.push({ id: cat.id, title: cat.title, photos });
  total += photos.length;
  console.log(`${cat.id}: ${photos.length}`);
}

const ts = `/** GENERATED by scripts/build-gallery.mjs — do not edit by hand. */

export interface GalleryCategory {
  id: string;
  title: string;
  photos: string[];
}

export const GALLERY: GalleryCategory[] = ${JSON.stringify(manifest, null, 2)};
`;
writeFileSync(path.join(repo, "src", "components", "gallery", "manifest.ts"), ts);

if (tempDir) rmSync(tempDir, { recursive: true, force: true });
console.log(`total: ${total} photos → public/gallery + manifest.ts`);
